CREATE DATABASE IF NOT EXISTS form DEFAULT CHARACTER SET utf8 COLLATE utf8_slovak_ci;

USE form;

DROP TABLE IF EXISTS mesto;

CREATE TABLE mesto{
	IDmesto INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nazov VARCHAR(100) NOT NULL
}ENGINE=InnoDB;	

DROP TABLE IF EXISTS user;

CREATE TABLE user(
	IDuser INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(100) NOT NULL,
	password VARCHAR(100) NOT NULL,
	meno VARCHAR(45) NOT NULL,
	priezvisko VARCHAR(45) NOT NULL,
	isAdmin BOOLEAN DEFAULT FALSE, 
	IDmesto INT UNSIGNED NOT NULL,
	FOREIGN KEY(IDmesto) REFERENCES mesto(IDmesto)
)ENGINE=InnoDB;